# Generated by Django 4.1.1 on 2025-01-03 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_remove_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='f_fabricacion',
            field=models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2015, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
